// All tour packages data
// Each package has: id, name, destination, duration, price, rating, type, image, isSoldOut

const packages = [
  {
    id: 1,
    name: "Hunza Valley Adventure",
    destination: "Hunza, Gilgit-Baltistan",
    duration: "7 Days / 6 Nights",
    price: 45000,
    rating: 4.9,
    type: "Mountains",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    isSoldOut: false,
    description: "Explore the magical Hunza Valley with breathtaking mountain views, ancient forts, and warm local culture. This package covers Karimabad, Attabad Lake, and Passu Cones.",
    itinerary: [
      "Day 1: Arrival in Islamabad, meet & greet",
      "Day 2: Drive to Hunza via Karakoram Highway",
      "Day 3: Visit Baltit Fort and Karimabad Bazaar",
      "Day 4: Attabad Lake boat ride and Gojal Valley",
      "Day 5: Passu Cones trek and Hussaini Bridge",
      "Day 6: Free day in Hunza, local food tour",
      "Day 7: Return journey to Islamabad",
    ],
    inclusions: ["Transport (AC coaster)", "Hotel accommodation", "Breakfast & Dinner", "Tour guide", "All entry tickets"],
    exclusions: ["Airfare", "Lunch", "Personal expenses", "Travel insurance"],
  },
  {
    id: 2,
    name: "Swat Valley Tour",
    destination: "Swat, KPK",
    duration: "5 Days / 4 Nights",
    price: 28000,
    rating: 4.7,
    type: "Mountains",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    isSoldOut: false,
    description: "Discover the Switzerland of Pakistan! Swat offers lush green valleys, crystal-clear rivers, and stunning mountain scenery perfect for nature lovers.",
    itinerary: [
      "Day 1: Departure from Lahore to Swat",
      "Day 2: Visit Mingora city and Swat Museum",
      "Day 3: Malam Jabba ski resort and Madyan",
      "Day 4: Kalam valley and Ushu Forest",
      "Day 5: Return journey",
    ],
    inclusions: ["Transport", "Hotel stay", "Breakfast daily", "Local guide"],
    exclusions: ["Lunch & Dinner", "Personal shopping", "Adventure sports fees"],
  },
  {
    id: 3,
    name: "Gwadar Beach Escape",
    destination: "Gwadar, Balochistan",
    duration: "4 Days / 3 Nights",
    price: 35000,
    rating: 4.5,
    type: "Beaches",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    isSoldOut: false,
    description: "Visit the beautiful coastal city of Gwadar with its pristine beaches, Hammerhead cliff, and amazing seafood. A hidden gem of Pakistan.",
    itinerary: [
      "Day 1: Flight to Gwadar, hotel check-in",
      "Day 2: Hammerhead cliff and Kund Malir beach",
      "Day 3: Ormara beach and seafood dinner",
      "Day 4: Return flight",
    ],
    inclusions: ["Return flight tickets", "Hotel", "Breakfast", "Beach transport"],
    exclusions: ["Meals other than breakfast", "Personal expenses"],
  },
  {
    id: 4,
    name: "Lahore Heritage Tour",
    destination: "Lahore, Punjab",
    duration: "3 Days / 2 Nights",
    price: 15000,
    rating: 4.8,
    type: "Cities",
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800",
    isSoldOut: false,
    description: "Experience the heart of Pakistan's culture and history. Lahore's Mughal architecture, amazing food street, and vibrant bazaars will leave you amazed.",
    itinerary: [
      "Day 1: Arrival, Badshahi Mosque, Lahore Fort",
      "Day 2: Shalimar Gardens, Walled City tour, Food Street",
      "Day 3: Minar-e-Pakistan, shopping, departure",
    ],
    inclusions: ["Hotel", "Breakfast", "City transport", "Guide"],
    exclusions: ["Meals", "Shopping", "Entry tickets"],
  },
  {
    id: 5,
    name: "Skardu Dreams",
    destination: "Skardu, Gilgit-Baltistan",
    duration: "8 Days / 7 Nights",
    price: 65000,
    rating: 5.0,
    type: "Mountains",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800",
    isSoldOut: true,
    description: "An unforgettable journey to Skardu, home of K2 base camp, Shangrila resort, and Deosai Plains. One of the world's highest plateaus!",
    itinerary: [
      "Day 1: Flight to Skardu",
      "Day 2: Katchura Lake and Shangrila Resort",
      "Day 3: Deosai National Park",
      "Day 4: Shigar Fort and Shigar Valley",
      "Day 5: Upper Kachura Lake trek",
      "Day 6: Satpara Lake and Skardu City",
      "Day 7: Free day, local market",
      "Day 8: Return flight",
    ],
    inclusions: ["Flights", "Full board meals", "Jeep transport", "Camping gear", "Guide"],
    exclusions: ["Personal expenses", "Tips", "Travel insurance"],
  },
  {
    id: 6,
    name: "Dubai City Break",
    destination: "Dubai, UAE",
    duration: "5 Days / 4 Nights",
    price: 120000,
    rating: 4.8,
    type: "International",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    isSoldOut: false,
    description: "Experience the luxury and grandeur of Dubai! Burj Khalifa, desert safari, Dubai Mall, and world-class shopping all in one amazing trip.",
    itinerary: [
      "Day 1: Arrival in Dubai, hotel check-in",
      "Day 2: Burj Khalifa, Dubai Mall, Fountain show",
      "Day 3: Desert Safari with BBQ dinner",
      "Day 4: Palm Jumeirah, Atlantis, JBR Beach",
      "Day 5: Gold Souk, Spice Souk, departure",
    ],
    inclusions: ["Return flight from Karachi", "4-star hotel", "Visa assistance", "Desert safari", "Burj Khalifa tickets"],
    exclusions: ["Meals (except safari dinner)", "Shopping", "Optional tours"],
  },
  {
    id: 7,
    name: "Murree & Nathiagali",
    destination: "Murree, Punjab",
    duration: "3 Days / 2 Nights",
    price: 18000,
    rating: 4.4,
    type: "Mountains",
    image: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800",
    isSoldOut: false,
    description: "A short getaway to the cool hills of Murree and Nathiagali. Perfect for families wanting to escape city heat and enjoy fresh mountain air.",
    itinerary: [
      "Day 1: Drive to Murree, Mall Road walk",
      "Day 2: Nathiagali hike, Mukshpuri top",
      "Day 3: Ayubia and return",
    ],
    inclusions: ["Transport", "Hotel", "Breakfast"],
    exclusions: ["Lunch & Dinner", "Cable car tickets", "Personal expenses"],
  },
  {
    id: 8,
    name: "Karachi Coastal Tour",
    destination: "Karachi, Sindh",
    duration: "4 Days / 3 Nights",
    price: 22000,
    rating: 4.3,
    type: "Beaches",
    image: "https://images.unsplash.com/photo-1509233725247-49e657c54213?w=800",
    isSoldOut: false,
    description: "Explore Pakistan's largest city with its beautiful beaches, historic landmarks, amazing street food, and vibrant nightlife culture.",
    itinerary: [
      "Day 1: Arrival, Clifton Beach, Do Darya",
      "Day 2: Quaid's Mausoleum, Pakistan Museum",
      "Day 3: Hawke's Bay and French Beach",
      "Day 4: Empress Market, Zainab Market, departure",
    ],
    inclusions: ["Hotel", "City transport", "Breakfast", "Guide"],
    exclusions: ["Flights", "Meals except breakfast", "Shopping"],
  },
  {
    id: 9,
    name: "Istanbul Explorer",
    destination: "Istanbul, Turkey",
    duration: "7 Days / 6 Nights",
    price: 180000,
    rating: 4.9,
    type: "International",
    image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800",
    isSoldOut: false,
    description: "Discover where East meets West in the magical city of Istanbul. Blue Mosque, Hagia Sophia, Bosphorus cruise, and the famous Grand Bazaar await you!",
    itinerary: [
      "Day 1: Arrival in Istanbul, hotel check-in",
      "Day 2: Hagia Sophia, Blue Mosque, Topkapi Palace",
      "Day 3: Bosphorus cruise, Galata Tower",
      "Day 4: Grand Bazaar, Spice Market shopping",
      "Day 5: Princes Islands day trip",
      "Day 6: Dolmabahçe Palace, Taksim Square",
      "Day 7: Departure",
    ],
    inclusions: ["Return flights", "5-star hotel", "Visa", "Daily breakfast", "Tours"],
    exclusions: ["Lunch & Dinner", "Personal shopping", "Optional activities"],
  },
  {
    id: 10,
    name: "Islamabad Capital Tour",
    destination: "Islamabad, ICT",
    duration: "2 Days / 1 Night",
    price: 10000,
    rating: 4.6,
    type: "Cities",
    image: "https://images.unsplash.com/photo-1630975781906-e6ad43534ce0?w=800",
    isSoldOut: false,
    description: "A quick trip to Pakistan's beautiful capital city. Faisal Mosque, Margalla Hills, and the cleanest city in Pakistan awaits you!",
    itinerary: [
      "Day 1: Faisal Mosque, Pakistan Monument, Daman-e-Koh",
      "Day 2: Margalla Hills hike, Centaurus Mall, departure",
    ],
    inclusions: ["Transport", "Hotel", "Breakfast", "Guide"],
    exclusions: ["Meals", "Entry tickets", "Personal expenses"],
  },
  {
    id: 11,
    name: "Fairy Meadows Trek",
    destination: "Nanga Parbat, GB",
    duration: "6 Days / 5 Nights",
    price: 55000,
    rating: 4.8,
    type: "Mountains",
    image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800",
    isSoldOut: true,
    description: "Trek through magical Fairy Meadows with direct views of Nanga Parbat (9th highest peak in the world). A true bucket-list adventure!",
    itinerary: [
      "Day 1: Drive from Islamabad to Raikot",
      "Day 2: Jeep to Tato, trek to Fairy Meadows",
      "Day 3: Beyal Camp exploration",
      "Day 4: Nanga Parbat Base Camp (optional)",
      "Day 5: Return trek to Tato",
      "Day 6: Drive back to Islamabad",
    ],
    inclusions: ["Transport", "Camping accommodation", "All meals", "Trekking guide", "Camping gear"],
    exclusions: ["Personal trekking equipment", "Travel insurance", "Tips"],
  },
  {
    id: 12,
    name: "Malaysia Family Fun",
    destination: "Kuala Lumpur, Malaysia",
    duration: "6 Days / 5 Nights",
    price: 150000,
    rating: 4.7,
    type: "International",
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
    isSoldOut: false,
    description: "Perfect family vacation to Malaysia! Petronas Towers, Genting Highlands, Langkawi beaches, and amazing halal food make this a must-visit destination.",
    itinerary: [
      "Day 1: Arrival in KL, check-in",
      "Day 2: Petronas Towers, KLCC Park, Aquaria",
      "Day 3: Genting Highlands and theme park",
      "Day 4: Batu Caves, Little India, Central Market",
      "Day 5: Langkawi Island day trip",
      "Day 6: Shopping and departure",
    ],
    inclusions: ["Return flights", "Hotel", "Breakfast", "Visa", "Selected tours"],
    exclusions: ["Theme park tickets", "Lunch & Dinner", "Shopping"],
  },
]

export default packages
